stages:
  - build-jar
  - build-docker
#test:
#  script:
  # If you need to run any migrations or configure the database, this 
  # would be the point to do it.  
#  - lein test
cache:
  paths:
  - target
  
build-jar:
   image: clojure:boot-2.7.1-alpine
   #image: clojure:lein-2.7.1-alpine
   stage: build-jar
   script:
   - boot build
   #- lein deps
   #- lein uberjar
   cache:
     paths:
       - ~/.m2
       - ~/.boot/cache/lib
       - ~/.boot/cache/bin
   artifacts:
    paths:
    - target/it-service-sse-1.2.0.jar
    expire_in: 1 week

build-docker:
  stage: build-docker
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
#    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
#    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
